using System.Text.Json;
using HipoSim.FinancialEngine;
using Xunit.Abstractions;

namespace HipoSim.FinancialEngine.Tests;

/// <summary>
/// SP02: runs every case of GoldenData/python-parity-cases.json (generated by tools/generate_parity_cases.py
/// with the original AutoFinance Pro engine) through the C# engine and compares the whole schedule and
/// every indicator. Acceptance: at most one cent of difference in money values and 1e-6 in rates.
/// Documented deviation: the last installment is flagged as balloon only when the balloon ratio is above 0.
/// </summary>
public class PythonParityTests(ITestOutputHelper output)
{
    private const double MoneyTolerance = 0.01;
    private const double RateTolerance = 1e-6;

    private static readonly Lazy<ParityFile> Golden = new(LoadGolden);

    public static TheoryData<string> CaseNames()
    {
        var names = new TheoryData<string>();
        foreach (var parityCase in Golden.Value.Cases)
        {
            names.Add(parityCase.Name);
        }

        return names;
    }

    [Theory]
    [MemberData(nameof(CaseNames))]
    public void Simulate_WhenSameInputAsPython_MatchesScheduleAndIndicators(string caseName)
    {
        var parityCase = Golden.Value.Cases.Single(candidate => candidate.Name == caseName);

        var comparison = Compare(parityCase);

        Assert.True(comparison.MaxMoneyDifference <= MoneyTolerance, $"{caseName}: money difference {comparison.MaxMoneyDifference}");
        Assert.True(comparison.MaxRateDifference <= RateTolerance, $"{caseName}: rate difference {comparison.MaxRateDifference}");
    }

    [Fact]
    public void Simulate_WhenAllParityCasesRun_ReportsTheMaximumObservedDifference()
    {
        var comparisons = Golden.Value.Cases.Select(Compare).ToList();

        var rows = comparisons.Sum(comparison => comparison.Rows);
        var maxMoney = comparisons.Max(comparison => comparison.MaxMoneyDifference);
        var maxRate = comparisons.Max(comparison => comparison.MaxRateDifference);
        var differingValues = comparisons.Sum(comparison => comparison.DifferingValues);

        output.WriteLine($"PARITY cases={comparisons.Count} rows={rows} maxMoneyDifference={maxMoney:0.######} maxRateDifference={maxRate:0.#########} differingValues={differingValues}");
        foreach (var comparison in comparisons.OrderByDescending(c => c.MaxMoneyDifference).Take(5))
        {
            output.WriteLine($"PARITY top: {comparison.Name} money={comparison.MaxMoneyDifference:0.######} rate={comparison.MaxRateDifference:0.#########}");
        }

        Assert.True(maxMoney <= MoneyTolerance);
        Assert.True(maxRate <= RateTolerance);
    }

    private static CaseComparison Compare(ParityCase parityCase)
    {
        var input = parityCase.Input;
        var result = new FinancialEngine().Simulate(new LoanSimulationInput(
            PropertyPrice: input.PropertyPrice,
            DownPayment: input.DownPayment,
            RateType: Enum.Parse<RateType>(input.RateType),
            AnnualRate: input.AnnualRate,
            TermInMonths: input.TermInMonths,
            StartDate: DateOnly.Parse(input.StartDate),
            CapitalizationFrequency: input.CapitalizationFrequency is null ? null : Enum.Parse<CapitalizationFrequency>(input.CapitalizationFrequency),
            GraceType: Enum.Parse<GraceType>(input.GraceType),
            GraceMonths: input.GraceMonths,
            BalloonRatio: input.BalloonRatio,
            BenefitAmount: input.BenefitAmount,
            MonthlyPropertyInsurance: input.MonthlyPropertyInsurance,
            MonthlyCreditLifeInsurance: input.MonthlyCreditLifeInsurance,
            AdministrativeExpenses: input.AdministrativeExpenses,
            AnnualDiscountRate: input.AnnualDiscountRate));

        var expectedRows = parityCase.Expected.Schedule;
        Assert.Equal(expectedRows.Count, result.Schedule.Count);

        var maxMoney = 0.0;
        var maxRate = 0.0;
        var differing = 0;

        void Money(double expected, double actual)
        {
            var difference = Math.Abs(expected - actual);
            maxMoney = Math.Max(maxMoney, difference);
            if (difference > 0)
            {
                differing++;
            }
        }

        void Rate(double expected, double actual)
        {
            var difference = Math.Abs(expected - actual);
            maxRate = Math.Max(maxRate, difference);
            if (difference > 0)
            {
                differing++;
            }
        }

        for (var index = 0; index < expectedRows.Count; index++)
        {
            var expected = expectedRows[index];
            var actual = result.Schedule[index];

            Assert.Equal(expected[0].GetInt32(), actual.Period);
            Assert.Equal(DateOnly.Parse(expected[1].GetString()!), actual.PaymentDate);
            Money(expected[2].GetDouble(), actual.Installment);
            Money(expected[3].GetDouble(), actual.Interest);
            Money(expected[4].GetDouble(), actual.Amortization);
            Money(expected[5].GetDouble(), actual.RemainingBalance);
            Money(expected[6].GetDouble(), actual.PropertyInsurance);
            Money(expected[7].GetDouble(), actual.CreditLifeInsurance);
            Money(expected[8].GetDouble(), actual.TotalPayment);
            Assert.Equal(expected[9].GetBoolean(), actual.IsGracePeriod);
            Assert.Equal(input.BalloonRatio > 0 && expected[10].GetBoolean(), actual.IsBalloonPayment);
        }

        var expectedSummary = parityCase.Expected.Summary;
        var summary = result.Summary;
        Money(expectedSummary.FinancedAmount, summary.FinancedAmount);
        Money(expectedSummary.RegularInstallment, summary.RegularInstallment);
        Money(expectedSummary.BalloonAmount, summary.BalloonAmount);
        Money(expectedSummary.TotalPaid, summary.TotalPaid);
        Money(expectedSummary.TotalInterest, summary.TotalInterest);
        Money(expectedSummary.AdditionalCosts, summary.AdditionalCosts);
        Money(expectedSummary.Npv, summary.Npv);
        Rate(expectedSummary.MonthlyIrr, summary.MonthlyIrr);
        Rate(expectedSummary.AnnualIrr, summary.AnnualIrr);
        Rate(expectedSummary.Tcea, summary.Tcea);

        return new CaseComparison(parityCase.Name, expectedRows.Count, maxMoney, maxRate, differing);
    }

    private static ParityFile LoadGolden()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "GoldenData", "python-parity-cases.json");
        var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        return JsonSerializer.Deserialize<ParityFile>(File.ReadAllText(path), options)
               ?? throw new InvalidOperationException("The parity file is empty.");
    }

    private sealed record CaseComparison(string Name, int Rows, double MaxMoneyDifference, double MaxRateDifference, int DifferingValues);

    private sealed record ParityFile(List<ParityCase> Cases);

    private sealed record ParityCase(string Name, ParityInput Input, ParityExpected Expected);

    private sealed record ParityInput(
        double PropertyPrice,
        double DownPayment,
        double BenefitAmount,
        string RateType,
        double AnnualRate,
        string? CapitalizationFrequency,
        int TermInMonths,
        string StartDate,
        string GraceType,
        int GraceMonths,
        double BalloonRatio,
        double MonthlyPropertyInsurance,
        double MonthlyCreditLifeInsurance,
        double AdministrativeExpenses,
        double? AnnualDiscountRate);

    private sealed record ParityExpected(List<List<JsonElement>> Schedule, ParitySummary Summary);

    private sealed record ParitySummary(
        double FinancedAmount,
        double RegularInstallment,
        double BalloonAmount,
        double TotalPaid,
        double TotalInterest,
        double AdditionalCosts,
        double Npv,
        double MonthlyIrr,
        double AnnualIrr,
        double Tcea);
}
