// <auto-generated />
using System;
using HipoSim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HipoSim.Api.Data.Migrations
{
    [DbContext(typeof(HipoSimDbContext))]
    [Migration("20261010203538_AddContactMessages")]
    partial class AddContactMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HipoSim.Api.Data.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("HipoSim.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedDataProcessingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_data_processing_at");

                    b.Property<DateTimeOffset>("AcceptedTermsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_terms_at");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_normalized");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_users_agency_id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_normalized");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('buyer', 'advisor')");
                        });
                });

            modelBuilder.Entity("HipoSim.Api.Data.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_contact_messages_created_at");

                    b.ToTable("contact_messages", (string)null);
                });

            modelBuilder.Entity("HipoSim.Api.Data.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("ConsentGrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_granted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_leads_agency_id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_leads_buyer_id");

                    b.HasIndex("SimulationId")
                        .HasDatabaseName("ix_leads_simulation_id");

                    b.ToTable("leads", null, t =>
                        {
                            t.HasCheckConstraint("ck_leads_status", "status IN ('New', 'InContact', 'AppointmentScheduled', 'Closed', 'Discarded')");
                        });
                });

            modelBuilder.Entity("HipoSim.Api.Data.LeadNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_notes_lead_id");

                    b.ToTable("lead_notes", (string)null);
                });

            modelBuilder.Entity("HipoSim.Api.Data.LeadStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_status_changes_lead_id");

                    b.ToTable("lead_status_changes", (string)null);
                });

            modelBuilder.Entity("HipoSim.Api.Data.StoredSimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_simulations_buyer_id");

                    b.ToTable("simulations", (string)null);
                });

            modelBuilder.Entity("HipoSim.Api.Data.AppUser", b =>
                {
                    b.HasOne("HipoSim.Api.Data.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HipoSim.Api.Data.Lead", b =>
                {
                    b.HasOne("HipoSim.Api.Data.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HipoSim.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HipoSim.Api.Data.StoredSimulation", null)
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HipoSim.Api.Data.LeadNote", b =>
                {
                    b.HasOne("HipoSim.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HipoSim.Api.Data.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HipoSim.Api.Data.LeadStatusChange", b =>
                {
                    b.HasOne("HipoSim.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HipoSim.Api.Data.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HipoSim.Api.Data.StoredSimulation", b =>
                {
                    b.HasOne("HipoSim.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
